services:
  - type: web
    name: flask-sqlite-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
