name: Flask CI

on:
  push:
    branches: [main]  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run app check (optional)
        run: |
          python -m compileall .

      # - name: Run tests (optional)
      #   run: |
      #     pytest  # if you have tests set up

      # - name: Deploy (optional)
      #   run: echo "Deploy step would go here"
